### ISSUE TITLE
Users can sign up

### ISSUE THREAD

**Issue by SamJT2021** [SamJT2021/howdy-partners-bookaroo-new#1]
As a new user,
So that I can sign up for Bookaroo
I want a sign up button on the welcome page

As a new user,
So that I can create my account
I want a sign up form on the sign up page

As a new user,
So that I can use my new account
I want to be redirected to the Newsfeed Page when I click sign up

As a new user,
So that I can correct any errors
I want an error message if my sign up does not work (validation failed)

**Comment by stevej763** [comment]
users will just have a username and a password for MVP
