### ISSUE TITLE
Logged in user can make a new post

### ISSUE THREAD

**Issue by SamJT2021** [SamJT2021/howdy-partners-bookaroo-new#4]
Fixed in ticket: #23 

As a logged in user,
So that I can create my new post
I want a 'New Post' button on the Newsfeed Page that takes me to a 'new-post' page

As a logged in user,
So that I can write my new post
I want a 'new post form' on the New Post page

As a logged in user,
So that I can share my new post
I want a share button on the 'new-post' page that shares my post
And I am redirected back to the Newsfeed Page

**Comment by BethLambertMatthews** [comment]
This should be closed by the ticket: **HP_bugfix_01: Bug fix for redirection correction after post made**
